spring.application.name=DairyFarmManagement

# MySQL Database Connection
spring.datasource.url=jdbc:mysql://dairy-farm-mysql-daityfarm-4e39.k.aivencloud.com:27564/dairy_farm?sslMode=REQUIRED

spring.datasource.username=avnadmin

spring.datasource.password=${DB_PASSWORD}

# MySQL Driver
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Server Port
server.port=8080